[language-server.codebook]
command = "codebook-lsp"
args = ["serve"]

[language-server.hx-lsp]
command = "hx-lsp"

[[language]]
name = "rust"
language-servers = [ "rust-analyzer", "codebook", "hx-lsp" ]

[[language]]
name = "cpp"
language-servers = [ "clangd", "codebook" ]

[[language]]
name = "python"
language-servers = ["ty", "ruff", "jedi", "pylsp", "codebook", "hx-lsp" ]

[[language]]
name = "markdown"
language-servers = [ "marksman", "markdown-oxide", "codebook", "hx-lsp" ]

[[language]]
name = "bash" 
language-servers = [ "bash-language-server", "codebook", "hx-lsp" ]
